name: workflow
on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: supernote-joplin
      - name: install and build dependencies
        uses: ./supernote-joplin/.github/install-build-dep
      - name: test
        run: |
          cd supernote-joplin
          npm ci
          npm run lint
          npm test

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6
        with:
          path: supernote-joplin
      - name: install and build dependencies
        uses: ./supernote-joplin/.github/install-build-dep
      - name: build-publish-to-npmjs
        run: |
          cd supernote-joplin
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm ci
          npm run dist
          npm publish
      - name: publish-to-github
        uses: softprops/action-gh-release@v2
        with:
           files: supernote-joplin/publish/net.individual-it.Supernote.jpl
